### ISSUE TITLE
pop index out of range

### ISSUE THREAD

**Issue by Floflobel** [terrelsa13/media_cleaner#39] opened 2022-09-06 16:56 UTC
Hello,

When I try to activate the following option, it always returns me an error and sends me all my media in JSON format.
```
multiuser_play_count_movie=1
```

```
...
:*[DELETE] - Movie - Test1 - Unplayed - Play Count: 0 - Created 382 days ago - Favorite: False - WhiteTag: False - BlackTag: False - Whitelisted: False - MovieID: XXXXX
-----------------------------------------------------------

pop index out of range

5017

[
    4086,
    4053,
    4046,
    1994,
    4026,
    4025,
...
```

[mumc_config.txt](https://github.com/terrelsa13/MUMC/files/9499180/mumc_config.txt)

Thank you for your help.

**Comment by terrelsa13** [comment] 2022-09-10 06:54
Hi @Floflobel 
I am not able to reproduce this issue with my setup. If you are not already using the [latest version of the script](https://github.com/terrelsa13/MUMC/releases/latest), please update to the latest version, change ```DEBUG=4```, run the script again so the error happens, and then attach the ```mumc_DEBUG.log``` file here.

If you are using an external IP to access your Emby/Jellyfin server, you may remove/change the external IP in the ```mumc_DEBUG.log```. However do **NOT** delete or change anything else in the ```mumc_DEBUG.log``` file.

**Comment by terrelsa13** [comment] 2022-10-08 16:59
@Floflobel I am not able to reproduce this issue.
Closing because no additional feedback has been provided to my last response.

**Closed as completed by terrelsa13** 2022-10-08 16:59 UTC
Labels: issue / bug
