### ISSUE TITLE
Exception When Selecting User. Try again.

### ISSUE THREAD

**Issue by kerpi4** [terrelsa13/media_cleaner#95] opened 2023-11-21 14:19 UTC
I keep getting this message after the configuration process on the first run. Only have one user. And on the second run:
`ConfigValueError: admin_settings > users > user_id cannot be empty ConfigValueError: admin_settings > users > user_name cannot be empty`

Jellyfin 10.8.12
MUMC 5.3.4
python 3.11.5
OS Arch Linux

**Comment by terrelsa13** [comment] 2023-11-22 13:44
Sounds like the script is having an issue adding the user. But instead of completely failing, it is creating the config but not populating the user info.

If I am able, I will look into this today. If I am not able, I will look into it this weekend after the holiday rush is over.

--------------------------
To temporarily bypass the config value errors, you can manually edit ```mumc_config.yaml``` and add the user's userId and the user's username in the locations the error is pointing to.

admin_settings > users > user_id:

admin_settings > users > user_name:

**Comment by terrelsa13** [comment] 2023-11-22 13:48
In hindsight, if only having a single user on the jellyfin server is not being handled correctly by the script. You can also try adding a second user to the jellyfin server. You do not need to select them during the first run of the script.

This may be the path of least resistance.

**Comment by terrelsa13** [comment] 2023-11-22 18:01
@kerpi4 I was able to reproduce this on my end. Issue should now be fixed with the [latest v5.3.6](https://github.com/terrelsa13/MUMC). Try it out. Let me know if you run into any more issue.

**Comment by kerpi4** [comment] 2023-11-22 18:51
The configuration goes smoothly, but on the second run i get this: https://pastebin.com/raw/36SuX0Gr

Same error as when I added the data manually or when I added second user with the previous version.

**Comment by terrelsa13** [comment] 2023-11-23 00:25
Yep. Good find!

A copy/paste error was causing the ```KeyError: 'extra'``` you are seeing.
Which led me to a config option ```dynamic_behavior``` that was recently added. Looks like I modified the config checker with the new option. But missed adding it to the config creator. Either way both are fixed.

Updates can be found using the [latest v5.3.7](https://github.com/terrelsa13/MUMC).

I will update the [latest release](https://github.com/terrelsa13/MUMC/releases) and the wiki with the ```dynamic_behavior``` option sometime this weekend. For now it is holiday time with the family.

I will be back online Saturday or Sunday to help you get setup and going if you are still having issues.

**Comment by terrelsa13** [comment] 2023-11-23 06:26
Was able to update the latest release and the wiki.
Should be good to go. Latest is now v5.3.8.

**Comment by kerpi4** [comment] 2023-11-23 07:34
Didn't get the chance to try v5.3.7 but with the latest 5.3.8 version everything seems to be working fine. Thank you!

**Comment by terrelsa13** [comment] 2023-11-25 21:51
Glad to hear it is working for you!
I will close this issue.
If you have any more problems let me know.

**Closed as completed by terrelsa13** 2023-11-25 21:51 UTC
Labels: issue / bug
